site_name: Merideum Docs
site_url: https://merideum.org/docs/
site_description: 'Documentation for the Merideum project.'
site_author: 'merideum.org'
docs_dir: docs/
repo_url: https://github.com/merideum/merideum-spec/
nav:
    - Home: index.md
theme:
    name: material
